Repository terraform-providers/terraform-provider-dome9, pull requests merged in 2019-11, with the labels that each got.

#7 Continuous compliance notification documentation
  examples/continuous_compliance/notification/main.tf
  website/docs/d/continuous_compliance_notification.html.markdown
  website/docs/r/continuous_compliance_notification.html.markdown
Labels: documentation, size/L

#11 Remove double timestamp from logger
  dome9/config.go
Labels: size/XS

#14 Documentation update for continuous_compliance_notification resource and data source
  website/docs/d/continuous_compliance_notification.html.markdown
  website/docs/r/continuous_compliance_notification.html.markdown
Labels: documentation, size/M

#16 Website sidebar update
  website/dome9.erb
Labels: documentation, size/XS

#21 Fix make lint - exclude vendor and increase timeout
  GNUmakefile
Labels: bug, size/XS

#20 Removed unnecessary loops functions
  dome9/data_source_dome9_continuous_compliance_policy.go
  dome9/resource_dome9_continuous_compliance_notification.go
  dome9/resource_dome9_continuous_compliance_policy.go
Labels: size/XS

#22 Add tflint process to Travis-CI and set go version to 1.13
  .travis.yml
  GNUmakefile
Labels: enhancement, size/M

#18 Mark secret key as sensitive and don't print it
  dome9/config.go
  dome9/provider.go
Labels: bug, size/XS

#25 Align the id property across the code and the documentation
  examples/cloudaccount/azure/main.tf
  examples/cloudaccount/gcp/main.tf
  website/docs/d/cloudaccount_aws.html.markdown
  website/docs/d/cloudaccount_azure.html.markdown
  website/docs/d/cloudaccount_gcp.html.markdown
  website/docs/d/continuous_compliance_notification.html.markdown
  website/docs/d/continuous_compliance_policy.html.markdown
  website/docs/d/iplist.html.markdown
Labels: bug, documentation, size/XS

#27 Fixed Continuous Compliance policy documentation typo
  website/docs/r/continuous_compliance_policy.html.markdown
Labels: bug, documentation, size/XS

#28 New resource and data source - rule set
  CHANGELOG.md
  dome9/common/providerconst/const.go
  dome9/common/resourcetype/resource_type.go
  dome9/common/testing/variable/variable.go
  dome9/config.go
  dome9/data_source_dome9_ruleset.go
  dome9/data_source_dome9_ruleset_test.go
  dome9/provider.go
  dome9/resource_dome9_ruleset.go
  dome9/resource_dome9_ruleset_test.go
  examples/rule_set/README.md
  examples/rule_set/main.tf
  go.mod
  go.sum
  vendor/github.com/dome9/dome9-sdk-go/services/compliance/continuous_compliance_notification/continuous_compliance_notification.go
  vendor/github.com/dome9/dome9-sdk-go/services/compliance/continuous_compliance_policy/continuous_compliance_policy.go
  vendor/github.com/dome9/dome9-sdk-go/services/rulebundles/rule_bundles.go
  vendor/github.com/dome9/dome9-sdk-go/services/rulebundles/service.go
  vendor/modules.txt
  website/docs/d/rule_set.html.markdown
  website/docs/r/rule_set.html.markdown
  website/dome9.erb
Labels: dependencies, documentation, new-data-source, new-resource, provider, size/XL
