Repository terraform-providers/terraform-provider-dome9, pull requests merged in 2019-10, with the labels that each got.

#2 Continuous compliance notification resource
  CHANGELOG.md
  dome9/common/resourcetype/resource_type.go
  dome9/common/testing/environmentvariable/environment_variable.go
  dome9/common/testing/variable/variable.go
  dome9/config.go
  dome9/data_source_dome9_cloudaccount_aws.go
  dome9/data_source_dome9_cloudaccount_aws_test.go
  dome9/data_source_dome9_cloudaccount_azure.go
  dome9/data_source_dome9_cloudaccount_azure_test.go
  dome9/data_source_dome9_cloudaccount_gcp.go
  dome9/data_source_dome9_cloudaccount_gcp_test.go
  dome9/data_source_dome9_continuous_compliance_notification.go
  dome9/data_source_dome9_continuous_compliance_notification_test.go
  dome9/data_source_dome9_continuous_compliance_policy.go
  dome9/data_source_dome9_continuous_compliance_policy_test.go
  dome9/data_source_dome9_iplist.go
  dome9/data_source_dome9_iplist_test.go
  dome9/provider.go
  dome9/resource_dome9_cloudaccount_aws_test.go
  dome9/resource_dome9_cloudaccount_azure.go
  dome9/resource_dome9_cloudaccount_azure_test.go
  dome9/resource_dome9_cloudaccount_gcp.go
  dome9/resource_dome9_cloudaccount_gcp_test.go
  dome9/resource_dome9_continuous_compliance_notification.go
  dome9/resource_dome9_continuous_compliance_notification_test.go
  dome9/resource_dome9_continuous_compliance_policy.go
  dome9/resource_dome9_continuous_compliance_policy_test.go
  dome9/resource_dome9_iplist_test.go
  examples/continuous_compliance/policy/main.tf
  go.mod
  go.sum
  vendor/modules.txt
Labels: new-resource, provider, size/XXL, tests

#3 Documentation fixes after first submission
  website/docs/d/cloudaccount_aws.html.markdown
  website/docs/d/cloudaccount_azure.html.markdown
  website/docs/d/cloudaccount_gcp.html.markdown
  website/docs/d/continuous_compliance_policy.html.markdown
  website/docs/d/iplist.html.markdown
  website/docs/index.html.markdown
  website/docs/r/cloudaccount_aws.html.markdown
  website/docs/r/cloudaccount_azure.html.markdown
  website/docs/r/cloudaccount_gcp.html.markdown
  website/docs/r/continuous_compliance_policy.html.markdown
  website/docs/r/iplist.html.markdown
Labels: documentation, size/L

#4 Removing unused environment variables
  dome9/common/testing/environmentvariable/environment_variable.go
Labels: size/XS

#5 Revendor the missing files for CC notifications
  vendor/github.com/dome9/dome9-sdk-go/services/compliance/continuous_compliance_notification/continuous_compliance_notification.go
  vendor/github.com/dome9/dome9-sdk-go/services/compliance/continuous_compliance_notification/service.go
Labels: bug, dependencies, size/L

#6 Update go mod to use latest SDK
  go.mod
  go.sum
  vendor/modules.txt
Labels: dependencies, size/XS
