Repository terraform-providers/terraform-provider-dome9, pull requests merged in 2019-12, with the labels that each got.

#29 Attach cloudaccount to OU on create
  dome9/data_source_dome9_cloudaccount_aws.go
  dome9/resource_dome9_cloudaccount_aws.go
  dome9/resource_dome9_cloudaccount_gcp.go
  go.mod
  go.sum
  vendor/github.com/dome9/dome9-sdk-go/services/cloudaccounts/aws/aws.go
  vendor/github.com/dome9/dome9-sdk-go/services/cloudaccounts/gcp/gcp.go
  vendor/modules.txt
  website/docs/d/cloudaccount_aws.html.markdown
  website/docs/r/cloudaccount_aws.html.markdown
  website/docs/r/cloudaccount_azure.html.markdown
  website/docs/r/cloudaccount_gcp.html.markdown
Labels: bug, dependencies, documentation, size/S

#30 Ruleset resource renaming
  dome9/common/resourcetype/resource_type.go
  examples/ruleset/README.md
  examples/ruleset/main.tf
  website/docs/d/ruleset.html.markdown
  website/docs/r/ruleset.html.markdown
  website/dome9.erb
Labels: documentation, size/S

#31 documentation for ruleset resource and data source
  website/docs/d/ruleset.html.markdown
  website/docs/r/ruleset.html.markdown
Labels: documentation, size/S

#33 New resource AWS security group
  dome9/common/providerconst/const.go
  dome9/common/resourcetype/resource_type.go
  dome9/common/testing/variable/variable.go
  dome9/config.go
  dome9/data_source_dome9_cloud_security_group_aws.go
  dome9/data_source_dome9_cloud_security_group_aws_test.go
  dome9/provider.go
  dome9/resource_dome9_cloud_security_group_aws.go
  dome9/resource_dome9_cloud_security_group_aws_test.go
  dome9/resource_dome9_cloudaccount_aws_test.go
  dome9/resource_dome9_continuous_compliance_notification_test.go
  examples/cloud_security_group/aws/README.md
  examples/cloud_security_group/aws/main.tf
  go.mod
  go.sum
  vendor/github.com/dome9/dome9-sdk-go/services/cloudsecuritygroup/securitygroupaws/securitygroupaws.go
  vendor/github.com/dome9/dome9-sdk-go/services/cloudsecuritygroup/securitygroupaws/service.go
  vendor/modules.txt
  website/docs/d/aws_security_group.html.markdown
  website/docs/d/cloudaccount_aws.html.markdown
  website/docs/r/aws_security_group.html.markdown
  website/dome9.erb
Labels: dependencies, documentation, new-data-source, new-resource, size/XXL, tests

#35 New resource role
  dome9/common/resourcetype/resource_type.go
  dome9/common/testing/variable/variable.go
  dome9/config.go
  dome9/data_source_dome9_role.go
  dome9/data_source_dome9_role_test.go
  dome9/provider.go
  dome9/resource_dome9_role.go
  dome9/resource_dome9_role_test.go
  examples/role/README.md
  examples/role/main.tf
  go.mod
  go.sum
  vendor/github.com/dome9/dome9-sdk-go/services/roles/role.go
  vendor/github.com/dome9/dome9-sdk-go/services/roles/service.go
  vendor/modules.txt
  website/docs/d/role.html.markdown
  website/docs/r/role.html.markdown
  website/dome9.erb
Labels: dependencies, documentation, new-data-source, new-resource, size/XL, tests

#36 Update support for AWS security group
  dome9/common/providerconst/const.go
  dome9/common/testing/variable/variable.go
  dome9/data_source_dome9_cloud_security_group_aws.go
  dome9/data_source_dome9_cloud_security_group_aws_test.go
  dome9/resource_dome9_cloud_security_group_aws.go
  dome9/resource_dome9_cloud_security_group_aws_test.go
  go.mod
  go.sum
  vendor/github.com/dome9/dome9-sdk-go/services/cloudsecuritygroup/securitygroupaws/securitygroupaws.go
  vendor/modules.txt
  website/docs/r/aws_security_group.html.markdown
Labels: dependencies, documentation, size/M, tests

#38 dome9 provider additional resources (role, security group)
  website/docs/d/aws_security_group.html.markdown
  website/docs/r/aws_security_group.html.markdown
  website/docs/r/role.html.markdown
Labels: documentation, size/S

#40 Sensitive strings handling
  dome9/resource_dome9_cloudaccount_azure.go
  dome9/resource_dome9_cloudaccount_gcp.go
Labels: size/XS

#42 Changing AWS security group resource name in testing
  dome9/common/testing/variable/variable.go
  dome9/resource_dome9_cloud_security_group_aws_test.go
Labels: bug, size/XS

#43 Update Tags and services use the same update SDK function
  dome9/resource_dome9_cloud_security_group_aws.go
Labels: bug, size/XS

#44 New resource: Organizational Unit
  dome9/common/resourcetype/resource_type.go
  dome9/common/testing/variable/variable.go
  dome9/config.go
  dome9/data_source_dome9_organizational_unit.go
  dome9/data_source_dome9_organizational_unit_test.go
  dome9/provider.go
  dome9/resource_dome9_organizational_unit.go
  dome9/resource_dome9_organizational_unit_test.go
  examples/organizational_unit/README.md
  examples/organizational_unit/main.tf
  go.mod
  go.sum
  vendor/github.com/dome9/dome9-sdk-go/services/cloudsecuritygroup/securitygroupaws/securitygroupaws.go
  vendor/github.com/dome9/dome9-sdk-go/services/organizationalunits/organizationalunit.go
  vendor/github.com/dome9/dome9-sdk-go/services/organizationalunits/service.go
  vendor/modules.txt
  website/docs/d/organizational_unit.html.markdown
  website/docs/r/organizational_unit.html.markdown
  website/dome9.erb
Labels: dependencies, documentation, new-data-source, new-resource, provider, size/XL

#46 Remove AWS update test
  dome9/common/testing/variable/variable.go
  dome9/resource_dome9_cloud_security_group_aws_test.go
Labels: bug, size/XS

#47 Azure resource re structure
  dome9/resource_dome9_cloudaccount_azure.go
  dome9/resource_dome9_cloudaccount_azure_test.go
  examples/cloudaccount/azure/main.tf
  website/docs/r/cloudaccount_azure.html.markdown
Labels: documentation, size/M

#48 GCP resource re structure
  dome9/common/providerconst/const.go
  dome9/common/testing/variable/variable.go
  dome9/resource_dome9_cloudaccount_gcp.go
  dome9/resource_dome9_cloudaccount_gcp_test.go
  examples/cloudaccount/gcp/main.tf
  website/docs/r/cloudaccount_gcp.html.markdown
Labels: bug, documentation, size/L

#41 New resource Azure security group
  dome9/common/providerconst/const.go
  dome9/common/resourcetype/resource_type.go
  dome9/common/testing/environmentvariable/environment_variable.go
  dome9/common/testing/variable/variable.go
  dome9/config.go
  dome9/data_source_dome9_cloud_security_group_aws_test.go
  dome9/data_source_dome9_cloud_security_group_azure.go
  dome9/data_source_dome9_cloud_security_group_azure_test.go
  dome9/data_source_dome9_cloudaccount_azure_test.go
  dome9/data_source_dome9_continuous_compliance_policy_test.go
  dome9/provider.go
  dome9/resource_dome9_cloud_security_group_aws_test.go
  dome9/resource_dome9_cloud_security_group_azure.go
  dome9/resource_dome9_cloud_security_group_azure_test.go
  dome9/resource_dome9_cloudaccount_azure.go
  dome9/resource_dome9_cloudaccount_azure_test.go
  dome9/resource_dome9_continuous_compliance_policy_test.go
  examples/cloud_security_group/azure/README.md
  examples/cloud_security_group/azure/main.tf
  go.sum
  vendor/github.com/dome9/dome9-sdk-go/services/cloudsecuritygroup/securitygroupazure/securitygroupazure.go
  vendor/github.com/dome9/dome9-sdk-go/services/cloudsecuritygroup/securitygroupazure/service.go
  vendor/modules.txt
  website/docs/d/azure_security_group.html.markdown
  website/docs/r/azure_security_group.html.markdown
  website/dome9.erb
Labels: dependencies, documentation, new-data-source, new-resource, size/XXL, tests

#49 New resource attach IAM safe
  dome9/common/resourcetype/resource_type.go
  dome9/common/testing/environmentvariable/environment_variable.go
  dome9/provider.go
  dome9/resource_dome9_attach_iam_safe.go
  dome9/resource_dome9_attach_iam_safe_test.go
  examples/attach_iam_safe/README.md
  examples/attach_iam_safe/main.tf
  go.mod
  go.sum
  vendor/github.com/dome9/dome9-sdk-go/services/cloudaccounts/aws/aws.go
  vendor/github.com/dome9/dome9-sdk-go/services/cloudaccounts/cloudaccounts.go
  vendor/modules.txt
  website/docs/r/attach_iam_safe.html.markdown
  website/dome9.erb
Labels: dependencies, documentation, new-data-source, new-resource, size/XL, tests

#50 Removed Attach IAM data source from provider main schema
  dome9/provider.go
Labels: size/XS

#52 Removing data from attachIAMSafe resource test
  dome9/resource_dome9_attach_iam_safe_test.go
Labels: bug, size/XS

#51 Support new field iam_safe in AWS cloud account
  dome9/data_source_dome9_cloudaccount_aws.go
  dome9/resource_dome9_cloudaccount_aws.go
Labels: size/M

#53 Remove tags from AWS security group test
  dome9/common/testing/variable/variable.go
  dome9/data_source_dome9_cloud_security_group_aws_test.go
  dome9/resource_dome9_cloud_security_group_aws_test.go
Labels: size/XS

#54 WIP - New resource user
  dome9/common/resourcetype/resource_type.go
  dome9/common/testing/variable/variable.go
  dome9/config.go
  dome9/data_source_dome9_user.go
  dome9/data_source_dome9_user_test.go
  dome9/provider.go
  dome9/resource_dome9_role_test.go
  dome9/resource_dome9_ruleset_test.go
  dome9/resource_dome9_user.go
  dome9/resource_dome9_user_test.go
  examples/user/README.md
  examples/user/main.tf
  vendor/github.com/dome9/dome9-sdk-go/services/users/service.go
  vendor/github.com/dome9/dome9-sdk-go/services/users/user.go
  vendor/modules.txt
  website/docs/d/user.html.markdown
  website/docs/r/user.html.markdown
Labels: dependencies, documentation, new-data-source, new-resource, size/XXL, tests

#58 IAM Safe Entity
  dome9/common/providerconst/const.go
  dome9/common/resourcetype/resource_type.go
  dome9/common/testing/variable/variable.go
  dome9/provider.go
  dome9/resource_dome9_attach_iam_safe.go
  dome9/resource_dome9_iam_safe_entity.go
  dome9/resource_dome9_iam_safe_entity_test.go
  examples/iam_safe_entity/README.md
  examples/iam_safe_entity/main.tf
  go.mod
  go.sum
  vendor/github.com/dome9/dome9-sdk-go/services/cloudaccounts/aws/aws.go
  vendor/github.com/dome9/dome9-sdk-go/services/cloudaccounts/cloudaccounts.go
  vendor/github.com/dome9/dome9-sdk-go/services/users/user.go
  vendor/modules.txt
  website/docs/r/iam_safe_entity.html.markdown
  website/dome9.erb
Labels: dependencies, documentation, new-resource, size/XL, tests

#57 SRL Support for Role resource
  dome9/common/providerconst/const.go
  dome9/common/testing/variable/variable.go
  dome9/data_source_dome9_role.go
  dome9/data_source_dome9_role_test.go
  dome9/resource_dome9_role.go
  dome9/resource_dome9_role_test.go
  dome9/resource_dome9_user_test.go
  dome9/schema_srl_configuration.go
  examples/role/main.tf
  website/docs/d/role.html.markdown
  website/docs/r/role.html.markdown
Labels: dependencies, documentation, enhancement, provider, size/XL

#59 Increase time to wait until attach IAM safe done
  dome9/common/testing/variable/variable.go
Labels: size/XS

#60 Test for update AWS security group
  dome9/common/testing/variable/variable.go
  dome9/resource_dome9_cloud_security_group_aws_test.go
Labels: size/S, tests

#61 Test for update Azure security group
  dome9/common/testing/variable/variable.go
  dome9/resource_dome9_cloud_security_group_azure_test.go
Labels: size/S, tests

#62 SRL Support for User resource
  dome9/data_source_dome9_user.go
  dome9/resource_dome9_role.go
  dome9/resource_dome9_user.go
  dome9/resource_dome9_user_test.go
  examples/user/main.tf
  go.mod
  go.sum
  vendor/github.com/dome9/dome9-sdk-go/services/users/user.go
  vendor/modules.txt
  website/docs/d/user.html.markdown
  website/docs/r/user.html.markdown
Labels: dependencies, documentation, new-field, size/L, tests

#63 Add restricted IAM safe entity to AWS cloud account
  dome9/data_source_dome9_cloudaccount_aws.go
  dome9/resource_dome9_cloudaccount_aws.go
  website/docs/d/cloudaccount_aws.html.markdown
  website/docs/r/cloudaccount_aws.html.markdown
Labels: documentation, new-field, size/M

#64 Dome9 provider doc resource chgs
  CHANGELOG.md
  website/docs/d/aws_security_group.html.markdown
  website/docs/d/azure_security_group.html.markdown
  website/docs/d/cloudaccount_aws.html.markdown
  website/docs/r/cloudaccount_aws.html.markdown
  website/docs/r/cloudaccount_gcp.html.markdown
Labels: documentation, size/M
