Repository terraform-providers/terraform-provider-dome9, pull requests merged in 2020-04, with the labels that each got.

#74 dome9_aws_security_group.external_id output fix
  dome9/resource_dome9_cloud_security_group_aws.go
Labels: size/XS

#80 Using go vet rather than go lint
  .travis.yml
  GNUmakefile
Labels: size/S

#77 Support new aws regions
  dome9/common/providerconst/const.go
  dome9/resource_dome9_cloudaccount_aws_test.go
  website/docs/r/cloudaccount_aws.html.markdown
Labels: documentation, size/XS
