Repository terraform-providers/terraform-provider-dome9, pull requests merged in 2020-01, with the labels that each got.

#65 Increase time to wait until attach IAM safe done
  dome9/common/testing/variable/variable.go
Labels: size/XS

#66 Documentation layout fix
  website/docs/r/azure_security_group.html.markdown
Labels: documentation, size/XS

#67 add missing reference to the `id` attr (aws)
  website/docs/r/cloudaccount_aws.html.markdown
Labels: documentation, size/XS

#68 ARN should be lowercase in this case
  website/docs/r/cloudaccount_aws.html.markdown
Labels: documentation, size/XS

#70 Fix ruleset cloud vendor types
  dome9/common/providerconst/const.go
  website/docs/r/ruleset.html.markdown
Labels: documentation, size/XS

#71 Using force delete to remove aws resource
  dome9/resource_dome9_cloudaccount_aws.go
  go.mod
  go.sum
  vendor/github.com/dome9/dome9-sdk-go/services/cloudaccounts/aws/aws.go
  vendor/github.com/dome9/dome9-sdk-go/services/cloudaccounts/cloudaccounts.go
  vendor/github.com/dome9/dome9-sdk-go/services/cloudsecuritygroup/securitygroupaws/securitygroupaws.go
  vendor/modules.txt
Labels: dependencies, size/XS
